opt: -ar 22050 -ac 1
max_num_processors: 20
num_commands: 100
ext: wav
datasets:
- name: null
  src_dir: /data1/xiepengyuan/audio/enqi_moxiaoqi/44k
  preprocessed_dir: /data1/xiepengyuan/audio/enqi_moxiaoqi/22k
  with_speaker_dir: false
