opt: -ar 22050 -ac 1
max_num_processors: 20
num_commands: 100
ext: wav
datasets:
- name: null
  src_dir: /data1/xiepengyuan/audio/tts/wangwen-mix/wangwen-mix_wav
  preprocessed_dir: /data1/xiepengyuan/audio/tts/wangwen-mix/en_wave
  with_speaker_dir: false
