opt: -ar 22050 -ac 1
max_num_processors: 20
num_commands: 100
ext: wav
datasets:
- name: null
  src_dir: /data1/xiepengyuan/audio/tts/tongtong/tongtong_wav
  preprocessed_dir: /data1/xiepengyuan/audio/tts/tongtong/Wave
  with_speaker_dir: false
